### ISSUE TITLE
Обновление requirements.txt

### ISSUE THREAD

**Issue by Veranchos** [fulstock/mrc_nested_ner_ru#3]
Добрый день!

Спасибо за вашу работу! Есть небольшая просьба: добавьте, пожалуйста, в файл requirements.txt версии пакетов, которые необходимо установить. Много времени тратится на разрешение конфликтов версий.  Кроме того, судя по всему, этот файл неполный, не хватает как минимум scikit-learn, scipy, возможно, чего-то еще, сейчас уже не могу воспроизвести.

**Comment by Veranchos** [comment]
Здравствуйте!
У меня еще несколько комментариев к запуску модели:

1) Если версия pytorch lightning>0.9, то там уже нет модуля metrics, появляется ошибка

```
from pytorch_lightning.metrics.metric import Metric
ModuleNotFoundError: No module named 'pytorch_lightning.metrics'

```
Решается это либо прописыванием нужной версии пакета в requirements, либо заменой 
`from pytorch_lightning.metrics.metric import Metric` на 
`from torchmetrics import Metric`

2) В utils нет модуля TGProgressBar (не критично)
```
File "../trainer.py", line 31, in <module>
    from utils.progress import TGProgressBar
ModuleNotFoundError: No module named 'utils.progress'
```
3) У класса BertLabeling нет add_model_specific_args, из-за чего все падает.
`type object 'BertLabeling' has no attribute 'add_model_specific_args'`

**Comment by molokanov50** [comment]
Добрый день!
Тоже пытаюсь провести тестирование предобученной модели, и мне не удается, т.к. у класса `BertLabeling` нет метода `add_model_specific_args`. 
Если попытаться пропустить вызов этого метода, то будет непонимание в атрибуте `seed`: с одной стороны, он запрашивается,
```
File "../tester.py", line 121, in test_bio
    seed_everything(args.seed, workers=True)
AttributeError: 'Namespace' object has no attribute 'seed'
```
но с другой стороны, при добавлении его в аргументы командной строки, он не распознается:
`tester.py: error: unrecognized arguments: --seed 33`.

**Comment by fulstock** [comment]
Добрый день! 

Спасибо большое, все ошибки были наконец исправлены и внесены нужные изменения. В `requirements.txt` теперь представлены точные версии, исправлены многочисленные баги. 

Если всё же возникнут новые, просьба снова открывать issue. Постараюсь исправлять гораздо быстрее и активнее.
